Salesforce_integration/objects/Cardtapp_Tapper__c.object
<CustomObject>
    <fields>
        <fullName>Member_external_ID__c</fullName>
        <label>Member external ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notify_Ambiguous_lead_contact_found__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify - Ambiguous lead/contact found</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_Existing_Contact_found__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify - Existing Contact found</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_existing_lead_found__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify - Existing Lead found</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_new_contact_created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify - New Contact created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notify_new_lead_created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify - New Lead created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesforce_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cardtapp Tappers</relationshipLabel>
        <relationshipName>Cardtapp_Tappers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cardtapp Tappers</relationshipLabel>
        <relationshipName>Cardtapp_Tappers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cardtapp_Tappers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Workflow_action__c</fullName>
        <label>Workflow action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cardtapp Tapper</label>
    <nameField>
        <displayFormat>CTT-{0000}</displayFormat>
        <label>Tapper Unique ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cardtapp Tappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_integration/objects/User.object
<CustomObject>
    <fields>
        <fullName>Cardtapp_External_Ids__c</fullName>
        <inlineHelpText>Separate multiple External ID tokens with commas</inlineHelpText>
        <label>Cardtapp External Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Salesforce_integration/classes/CardtappAttachTapper.cls
public with sharing class CardtappAttachTapper {
    
    static final string NEW_CONTACT_CREATED_WORKFLOW_ACTION_NAME = 'New Contact created';
    static final string NEW_LEAD_CREATED_WORKFLOW_ACTION_NAME = 'New Lead created';
    static final string EXISTING_CONTACT_FOUND_WORKFLOW_ACTION_NAME = 'Existing Contact found';
    static final string EXISTING_LEAD_FOUND_WORKFLOW_ACTION_NAME = 'Existing Lead found';
    static final string AMBIGUOUS_LEAD_CONTACT_FOUND_WORKFLOW_ACTION_NAME = 'Ambiguous Lead/Contact found';
    
    public static Cardtapp_Tapper__c AssociateUserToTapper(Cardtapp_Tapper__c t) {
    	
    	if (t.Member_external_id__c == null || t.Member_external_id__c == '') {
    		return t;
    	}
    	
    	string search_token = '%' + CardtappQueryHelper.MakeSafer(t.Member_external_id__c) + '%';
    	List<User> users = [SELECT Id, Cardtapp_notifications__c FROM User WHERE Cardtapp_External_Ids__c LIKE :search_token LIMIT 1];
    	    	
    	if (users.size() != 0) {
    		
    		User u = users[0];
    		t.Salesforce_User__c = u.Id;
    		
    		if (u.Cardtapp_notifications__c != null && u.Cardtapp_notifications__c != '') {
    			
	    		t.Notify_new_contact_created__c =  (u.Cardtapp_notifications__c.toLowerCase().contains('new contact created'));
	    		t.Notify_new_lead_created__c = (u.Cardtapp_notifications__c.toLowerCase().contains('new lead created'));
	    		t.Notify_existing_contact_found__c = (u.Cardtapp_notifications__c.toLowerCase().contains('existing contact found'));
	    		t.Notify_existing_lead_found__c = (u.Cardtapp_notifications__c.toLowerCase().contains('existing lead found'));
	    		t.Notify_Ambiguous_lead_contact_found__c = (u.Cardtapp_notifications__c.toLowerCase().contains('ambiguous lead/contact found'));
    		}	
    	}
    	 return t;
    }

    
     public static Cardtapp_Tapper__c LookupCreateSObject(  Cardtapp_Tapper__c t, 
     														String companyName, 
     														String leadSource, 
     														string createObjectType, 
     														boolean doLookupLead) {
     															
		Boolean createObjectTypeIsContact = (createObjectType == 'Contact') ? true : false;
		Boolean createObjectTypeIsLead = (createObjectType == 'Lead') ? true : false;

		// Only works for creating Contacts and Leads
		if (!createObjectTypeIsContact && !createObjectTypeIsLead) {
			return t;
		}
     
     	List<Contact> contactSearchResult = CardtappAttachTapperHelper.FindExistingSobject(t,'Contact');   	
    	
    	if (contactSearchResult.size() >= 2) {
    		
    		t.Workflow_action__c = AMBIGUOUS_LEAD_CONTACT_FOUND_WORKFLOW_ACTION_NAME;
    		// Do nothing because search result is ambiguous    

    		return t;		
    	} else if (contactSearchResult.size() == 1) {
    		// Associate Tapper to Contact
    		t.Salesforce_Contact__c = contactSearchResult[0].Id;
			t.Workflow_action__c = EXISTING_CONTACT_FOUND_WORKFLOW_ACTION_NAME;
			
    		return t;
    	}
		
		if (doLookupLead) {
			// Lookup in Lead object
	    	List<Lead> leadSearchResult = CardtappAttachTapperHelper.FindExistingSobject(t,'Lead');	
	
	    	if (leadSearchResult.size() >= 2) {

	    		t.Workflow_action__c = AMBIGUOUS_LEAD_CONTACT_FOUND_WORKFLOW_ACTION_NAME;
    			// Do nothing because search result is ambiguous    

	    		return t;		
	    	} else if (leadSearchResult.size() == 1) {
	    		// Associate Tapper to Lead	    		
	    		t.Salesforce_Lead__c = leadSearchResult[0].Id;
				t.Workflow_action__c = EXISTING_LEAD_FOUND_WORKFLOW_ACTION_NAME;
			
	    		return t;
	    	} 	    		
		}
		
		if (createObjectTypeIsContact) {
			
			// Retrieve AccountID
			Account a = CardtappAttachTapperHelper.GetOrCreateDefaultAccount(companyName);
					
    		// Create new contact
    		Id newContactId = CardtappAttachTapperHelper.CreateNewContactFromTapperRecord(t,a,leadSource);
    		
    		// Associate Tapper to Contact
    		t.Salesforce_Contact__c = newContactId;

			// Record workflow action type
			t.Workflow_action__c = NEW_CONTACT_CREATED_WORKFLOW_ACTION_NAME;
			
		} else {
    		
    		// Create new lead
    		Id newLeadId = CardtappAttachTapperHelper.CreateNewLeadFromTapperRecord(t,companyName,leadSource);
    		
    		// Associate Tapper to Lead
    		t.Salesforce_Lead__c = newLeadId;

			// Record workflow action type
			t.Workflow_action__c = NEW_LEAD_CREATED_WORKFLOW_ACTION_NAME;

    	}    	
     
     	return t;
     }
    
}