Salesforce_integration/objects/Cardtapp_Tapper__c.object
<CustomObject>
    <fields>
        <fullName>Member_external_ID__c</fullName>
        <label>Member external ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cardtapp Tappers</relationshipLabel>
        <relationshipName>Cardtapp_Tappers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cardtapp Tappers</relationshipLabel>
        <relationshipName>Cardtapp_Tappers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cardtapp_Tappers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cardtapp Tapper</label>
    <nameField>
        <displayFormat>CTT-{0000}</displayFormat>
        <label>Tapper Unique ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cardtapp Tappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_integration/objects/User.object
<CustomObject>
    <fields>
        <fullName>Cardtapp_External_Ids__c</fullName>
        <inlineHelpText>Separate multiple External ID tokens with commas</inlineHelpText>
        <label>Cardtapp External Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

Salesforce_integration/classes/AttachCardtappTapper.cls
public with sharing class AttachCardtappTapper {
    
    public static Cardtapp_Tapper__c AssociateUserToTapper(Cardtapp_Tapper__c t) {
    	
    	if (t.Member_external_id__c == null || t.Member_external_id__c == '') {
    		return t;
    	}
    	
    	string search_token = '%' + t.Member_external_id__c + '%';
    	List<User> users = [SELECT Id FROM User WHERE Cardtapp_External_Ids__c LIKE :search_token LIMIT 1];
    	
    	if (users.size() != 0) {
    		
    		User u = users[0];
    		t.Salesforce_User__c = u.Id;
    	}
    	
    	 return t;
    }

    public static Cardtapp_Tapper__c LookupContactCreateContact(Cardtapp_Tapper__c t, String companyName, String leadSource) {
    	
		Account a = AttachCardtappTapperHelper.GetOrCreateDefaultAccount(companyName);
    	
    	List<Contact> searchResult = AttachCardtappTapperHelper.FindExistingContact(t);
    	
    	if (searchResult.size() == 0) {
    		// Create new contact
    		Id newContactId = AttachCardtappTapperHelper.CreateNewContactFromTapperRecord(t,a,leadSource);
    		
    		// Associate Tapper to Contact
    		t.Salesforce_Contact__c = newContactId;
    		
    	} else if (searchResult.size() == 1) {
    		// Associate Tapper to Contact
    		
    		t.Salesforce_Contact__c = searchResult[0].Id;
    		
    	} else {
    		// Do nothing because search result is ambiguous
    	}
    	
    	return t;
    }    

    public static Cardtapp_Tapper__c LookupContactCreateLead(Cardtapp_Tapper__c t, String companyName, String leadSource) {
    	
    	List<Contact> searchResult = AttachCardtappTapperHelper.FindExistingContact(t);
    	
    	System.debug('Returned Contact list in LookupContactCreateLead contained ' + searchResult.size() + ' contacts.');
    	
    	if (searchResult.size() == 0) {
    		// Create new lead
    		Id newLeadId = AttachCardtappTapperHelper.CreateNewLeadFromTapperRecord(t,companyName,leadSource);
    		
    		// Associate Tapper to Lead
    		t.Salesforce_Lead__c = newLeadId;
    		
    	} else if (searchResult.size() == 1) {
    		// Associate Tapper to Contact
    		
    		t.Salesforce_Contact__c = searchResult[0].Id;
    		System.debug ('Associating Tapper to Contact with ID ' + t.Salesforce_Contact__c);
    		
    	} else {
    		// Do nothing because search result is ambiguous
    	}
    	
    	return t;    	
    }    
    
}